exports.qualities = [
	"Normal",
	"Genuine",
	"Vintage",
	"rarity3",
	"Unusual",
	"Unique",
	"Community",
	"Valve",
	"Self-Made",
	"Customized",
	"Strange",
	"Completed",
	"Haunted",
	"Collector's",
	"Decorated Weapon"
]

exports.quality = {
	"Normal":0,
	"Genuine":1,
	"Vintage":3,
	"rarity3":4,
	"Unusual":5,
	"Unique":6,
	"Community":7,
	"Valve":8,
	"Self-Made":9,
	"Customized":10,
	"Strange":11,
	"Completed":12,
	"Haunted":13,
	"Collector's":14,
	"Decorated Weapon":15,
	0:"Normal",
	1:"Genuine",
	3:"Vintage",
	4:"rarity3",
	5:"Unusual",
	6:"Unique",
	7:"Community",
	8:"Valve",
	9:"Self-Made",
	10:"Customized",
	11:"Strange",
	12:"Completed",
	13:"Haunted",
	14:"Collector's",
	15:"Decorated Weapon"
};

exports.killstreaks = [
	"Professional Killstreak",
	"Specialized Killstreak",
	"Killstreak"
];

exports.killstreak = {
	"Professional Killstreak":3,
	"Specialized Killstreak":2,
	"Killstreak":1
};

exports.effects = [
	"Flying Bits",
	"Nemesis Burst",
	"Holy Glow",
	"Green Confetti",
	"Purple Confetti",
	"Haunted Ghosts",
	"Green Energy",
	"Purple Energy",
	"Circling TF Logo",
	"Massed Flies",
	"Burning Flames",
	"Scorching Flames",
	"Searing Plasma",
	"Vivid Plasma",
	"Sunbeams",
	"Circling Peace Sign",
	"Circling Heart",
	"Stormy Storm",
	"Blizzardy Storm",
	"Nuts n' Bolts",
	"Orbiting Planets",
	"Eerie Orbiting Fire",
	"Orbiting Fire",
	"Bubbling",
	"Smoking",
	"Steaming",
	"Flaming Lantern",
	"Cloudy Moon",
	"Cauldron Bubbles",
	"Knifestorm",
	"Misty Skull",
	"Harvest Moon",
	"It's A Secret To Everybody",
	"Stormy 13th Hour",
	"Kill-a-Watt",
	"Terror-Watt",
	"Cloud 9",
	"Aces High",
	"Dead Presidents",
	"Miami Nights",
	"Disco Beat Down",
	"Phosphorous",
	"Sulphurous",
	"Memory Leak",
	"Overclocked",
	"Electrostatic",
	"Power Surge",
	"Anti-Freeze",
	"Time Warp",
	"Green Black Hole",
	"Roboactive",
	"Arcana",
	"Spellbound",
	"Chiroptera Venenata",
	"Poisoned Shadows",
	"Something Burning This Way Comes",
	"Hellfire",
	"Darkblaze",
	"Demonflame",
	"Bonzo The All-Gnawing",
	"Amaranthine",
	"Stare From Beyond",
	"The Ooze",
	"Ghastly Ghosts Jr",
	"Haunted Phantasm Jr",
	"Frostbite",
	"Molten Mallard",
	"Morning Glory",
	"Death at Dusk",
	"Abduction",
	"Atomic",
	"Subatomic",
	"Electric Hat Protector",
	"Magnetic Hat Protector",
	"Voltaic Hat Protector",
	"Galactic Codex",
	"Ancient Codex",
	"Nebula",
	"Death by Disco",
	"It's a mystery to everyone",
	"It's a puzzle to me",
	"Ether Trail",
	"Nether Trail",
	"Ancient Eldritch",
	"Eldritch Flame",
	"Neutron Star",
	"Tesla Coil",
	"Starstorm Insomnia",
	"Starstorm Slumber",
	"Brain Drain",
	"Open Mind",
	"Head of Steam",
	"The Galactic Gateway",
	"The Eldritch Opening",
	"The Dark Doorway",
	"Ring of Fire",
	"Vicious Circle",
	"White Lightning",
	"Omniscient Orb",
	"Clairvoyance",
	"Fifth Dimension",
	"Vicious Vortex",
	"Menacing Miasma",
	"Abyssal Aura",
	"Wicked Wood",
	"Ghastly Grove",
	"Mystical Medley",
	"Ethereal Essence",
	"Twisted Radiance",
	"Violet Vortex",
	"Verdant Vortex",
	"Valiant Vortex",
	"Sparkling Lights",
	"Frozen Icefall",
	"Fragmented Gluons",
	"Fragmented Quarks",
	"Fragmented Photons",
	"Defragmenting Reality",
	"Fragmenting Reality",
	"Refragmenting Reality",
	"Snowfallen",
	"Snowblinded",
	"Pyroland Daydream",
	"Hot",
	"Isotope",
	"Cool",
	"Energy Orb",
	"Showstopper",
	"Holy Grail",
	"'72",
	"Fountain of Delight",
	"Screaming Tiger",
	"Skill Gotten Gains",
	"Midnight Whirlwind",
	"Silver Cyclone",
	"Mega Strike",
	"Haunted Phantasm",
	"Ghastly Ghosts",
	"Hellish Inferno",
	"Spectral Swirl",
	"Infernal Flames",
	"Infernal Smoke",
	"Acidic Bubbles of Envy",
	"Flammable Bubbles of Attraction",
	"Poisonous Bubbles of Regret",
	"Roaring Rockets",
	"Spooky Night",
	"Ominous Night",
	"Bewitched",
	"Accursed",
	"Enchanted",
	"Static Mist",
	"Eerie Lightning",
	"Terrifying Thunder",
	"Jarate Shock",
	"Nether Void",
	"Good-Hearted Goodies",
	"Wintery Wisp",
	"Arctic Aurora",
	"Winter Spirit",
	"Festive Spirit",
	"Magical Spirit"
]

exports.effect = {  
	"Particle 1":1,
	"Flying Bits":2,
	"Nemesis Burst":3,
	"Community Sparkle":4,
	"Holy Glow":5,
	"Green Confetti":6,
	"Purple Confetti":7,
	"Haunted Ghosts":8,
	"Green Energy":9,
	"Purple Energy":10,
	"Circling TF Logo":11,
	"Massed Flies":12,
	"Burning Flames":13,
	"Scorching Flames":14,
	"Searing Plasma":15,
	"Vivid Plasma":16,
	"Sunbeams":17,
	"Circling Peace Sign":18,
	"Circling Heart":19,
	"Map Stamps":20,
	"Genteel Smoke":28,
	"Stormy Storm":29,
	"Blizzardy Storm":30,
	"Nuts n' Bolts":31,
	"Orbiting Planets":32,
	"Orbiting Fire":33,
	"Bubbling":34,
	"Smoking":35,
	"Steaming":36,
	"Flaming Lantern":37,
	"Cloudy Moon":38,
	"Cauldron Bubbles":39,
	"Eerie Orbiting Fire":40,
	"Knifestorm":43,
	"Misty Skull":44,
	"Harvest Moon":45,
	"It's A Secret To Everybody":46,
	"Stormy 13th Hour":47,
	"Attrib_Particle55":55,
	"Kill-a-Watt":56,
	"Terror-Watt":57,
	"Cloud 9":58,
	"Aces High":59,
	"Dead Presidents":60,
	"Miami Nights":61,
	"Disco Beat Down":62,
	"Phosphorous":63,
	"Sulphurous":64,
	"Memory Leak":65,
	"Overclocked":66,
	"Electrostatic":67,
	"Power Surge":68,
	"Anti-Freeze":69,
	"Time Warp":70,
	"Green Black Hole":71,
	"Roboactive":72,
	"Arcana":73,
	"Spellbound":74,
	"Chiroptera Venenata":75,
	"Poisoned Shadows":76,
	"Something Burning This Way Comes":77,
	"Hellfire":78,
	"Darkblaze":79,
	"Demonflame":80,
	"Bonzo The All-Gnawing":81,
	"Amaranthine":82,
	"Stare From Beyond":83,
	"The Ooze":84,
	"Ghastly Ghosts Jr":85,
	"Haunted Phantasm Jr":86,
	"Frostbite":87,
	"Molten Mallard":88,
	"Morning Glory":89,
	"Death at Dusk":90,
	"Abduction":91,
	"Atomic":92,
	"Subatomic":93,
	"Electric Hat Protector":94,
	"Magnetic Hat Protector":95,
	"Voltaic Hat Protector":96,
	"Galactic Codex":97,
	"Ancient Codex":98,
	"Nebula":99,
	"Death by Disco":100,
	"It's a mystery to everyone":101,
	"It's a puzzle to me":102,
	"Ether Trail":103,
	"Nether Trail":104,
	"Ancient Eldritch":105,
	"Eldritch Flame":106,
	"Neutron Star":107,
	"Tesla Coil":108,
	"Starstorm Insomnia":109,
	"Starstorm Slumber":110,
	"Brain Drain":111,
	"Open Mind":112,
	"Head of Steam":113,
	"The Galactic Gateway":114,
	"The Eldritch Opening":115,
	"The Dark Doorway":116,
	"Ring of Fire":117,
	"Vicious Circle":118,
	"White Lightning":119,
	"Omniscient Orb":120,
	"Clairvoyance":121,
	"Fifth Dimension":122,
	"Vicious Vortex":123,
	"Menacing Miasma":124,
	"Abyssal Aura":125,
	"Wicked Wood":126,
	"Ghastly Grove":127,
	"Mystical Medley":128,
	"Ethereal Essence":129,
	"Twisted Radiance":130,
	"Violet Vortex":131,
	"Verdant Vortex":132,
	"Valiant Vortex":133,
	"Sparkling Lights":134,
	"Frozen Icefall":135,
	"Fragmented Gluons":136,
	"Fragmented Quarks":137,
	"Fragmented Photons":138,
	"Defragmenting Reality":139,
	"Fragmenting Reality":141,
	"Refragmenting Reality":142,
	"Snowfallen":143,
	"Snowblinded":144,
	"Pyroland Daydream":145,
	"Hot":701,
	"Isotope":702,
	"Cool":703,
	"Energy Orb":704,
	"Attrib_Particle2001":2001,
	"Attrib_Particle2002":2002,
	"Attrib_Particle2003":2003,
	"Attrib_Particle2004":2004,
	"Attrib_Particle2005":2005,
	"Attrib_Particle2006":2006,
	"Attrib_Particle2007":2007,
	"Attrib_Particle2008":2008,
	"Showstopper":3001,
	"Holy Grail":3003,
	"'72":3004,
	"Fountain of Delight":3005,
	"Screaming Tiger":3006,
	"Skill Gotten Gains":3007,
	"Midnight Whirlwind":3008,
	"Silver Cyclone":3009,
	"Mega Strike":3010,
	"Haunted Phantasm":3011,
	"Ghastly Ghosts":3012,
	"Hellish Inferno":3013,
	"Spectral Swirl":3014,
	"Infernal Flames":3015,
	"Infernal Smoke":3016,
	"Acidic Bubbles of Envy":3017,
	"Flammable Bubbles of Attraction":3018,
	"Poisonous Bubbles of Regret":3019,
	"Roaring Rockets":3020,
	"Spooky Night":3021,
	"Ominous Night":3022,
	"Bewitched":3023,
	"Accursed":3024,
	"Enchanted":3025,
	"Static Mist":3026,
	"Eerie Lightning":3027,
	"Terrifying Thunder":3028,
	"Jarate Shock":3029,
	"Nether Void":3030,
	"Good-Hearted Goodies":3031,
	"Wintery Wisp":3032,
	"Arctic Aurora":3033,
	"Winter Spirit":3034,
	"Festive Spirit":3035,
	"Magical Spirit":3036,
	"Attrib_Particle22001":22001,
	"Attrib_Particle22002":22002,
	"Attrib_Particle22003":22003,
	"Attrib_Particle22004":22004,
	"Attrib_Particle22005":22005,
	"Attrib_Particle22006":22006,
	"Attrib_Particle22007":22007,
	"Attrib_Particle22008":22008
}

exports.skins = [
	// War paints first because of Mk.II and stuffs
	"Wrapped Reviver Mk.II",
	"Carpet Bomber Mk.II",
	"Masked Mender Mk.II",
	"Woodland Warrior Mk.II",
	"Forest Fire Mk.II",
	"Backwoods Boomstick Mk.II",
	"Woodsy Widowmaker Mk.II",
	"Night Owl Mk.II",
	"Iron Wood Mk.II",
	"Plaid Potshotter Mk.II",
	"Bovine Blazemaker Mk.II",
	"Civil Servant Mk.II",
	"Smalltown Bringdown Mk.II",
	"Civic Duty Mk.II",
	"Dead Reckoner Mk.II",
	"Autumn Mk.II",
	"Nutcracker Mk.II",
	"Macabre Web Mk.II",
	"Bloom Buffed",
	"Quack Canvassed",
	"Bank Rolled",
	"Merc Stained",
	"Kill Covered",
	"Fire Glazed",
	"Pizza Polished",
	"Bonk Varnished",
	"Star Crossed",
	"Clover Camo'd",
	"Freedom Wrapped",
	"Cardboard Boxed",
	"Dream Piped",
	"Miami Element",
	"Neo Tokyo",
	"Geometrical Teams",
	"Bomber Soul",
	"Uranium",
	"Cabin Fevered",
	"Polar Surprise",
	"Hana",
	"Dovetailed",
	"Cosmic Calamity",
	"Hazard Warning",
	"Mosaic",
	"Jazzy",
	"Alien Tech",
	"Damascus & Mahogany",
	"Skull Study",
	"Haunted Ghosts",
	"Spectral Shimmered",
	"Spirit of Halloween",
	"Horror Holiday",
	"Totally Boned",
	"Electroshocked",
	"Ghost Town",
	"Tumor Toasted",
	"Calavera Canvas",
	"Snow Covered",
	"Frost Ornamented",
	"Smissmas Village",
	"Igloo",
	"Seriously Snowed",
	"Smissmas Camo",
	"Sleighin' Style",
	"Alpine",
	"Gift Wrapped",
	"Winterland Wrapped",
	"Yeti Coated",
	"Park Pigmented",
	"Mannana Peeled",
	"Macaw Masked",
	"Sax Waxed",
	"Anodized Aloha",
	"Bamboo Brushed",
	"Tiger Buffed",
	"Croc Dusted",
	"Piña Polished",
	"Leopard Printed",
	"Dragon Slayer",
	"Smissmas Sweater",

	// Non war paints
	"Red Rock Roscoe",
	"Sand Cannon",
	"Wrapped Reviver",
	"Psychedelic Slugger",
	"Carpet Bomber",
	"Masked Mender",
	"Woodland Warrior",
	"Purple Range",
	"Sudden Flurry",
	"Forest Fire",
	"King of the Jungle",
	"Night Terror",
	"Backwoods Boomstick",
	"Woodsy Widowmaker",
	"Night Owl",
	"Tartan Torpedo",
	"Rustic Ruiner",
	"Barn Burner",
	"Homemade Heater",
	"Lumber From Down Under",
	"Iron Wood",
	"Country Crusher",
	"Plaid Potshotter",
	"Shot in the Dark",
	"Blasted Bombardier",
	"Reclaimed Reanimator",
	"Antique Annihilator",
	"Old Country",
	"American Pastoral",
	"Backcountry Blaster",
	"Bovine Blazemaker",
	"War Room",
	"Treadplate Tormenter",
	"Bogtrotter",
	"Earth, Sky and Fire",
	"Hickory Hole-Puncher",
	"Spruce Deuce",
	"Team Sprayer",
	"Rooftop Wrangler",
	"Civil Servant",
	"Citizen Pain",
	"Local Hero",
	"Mayor",
	"Smalltown Bringdown",
	"Civic Duty",
	"Liquid Asset",
	"Black Dahlia",
	"Lightning Rod",
	"Pink Elephant",
	"Flash Fryer",
	"Spark of Life",
	"Dead Reckoner",
	"Shell Shocker",
	"Current Event",
	"Turbine Torcher",
	"Brick House",
	"Sandstone Special",
	"Aqua Marine",
	"Low Profile",
	"Thunderbolt",
	"Autumn",
	"Nutcracker",
	"Pumpkin Patch",
	"Macabre Web",
	"Boneyard",
	"Wildwood",
	"Balloonicorn",
	"Rainbow",
	"Sweet Dreams",
	"Blue Mew",
	"Brain Candy",
	"Stabbed to Hell",
	"Flower Power",
	"Mister Cuddles",
	"Shot to Hell",
	"Torqued to Hell",
	"Coffin Nail",
	"Top Shelf",
	"Dressed to Kill",
	"High Roller's",
	"Warhawk",
	"Blitzkrieg",
	"Airwolf",
	"Corsair",
	"Butcher Bird",
	"Killer Bee",
	"Red Bear"
]

exports.skin = {
	"Wrapped Reviver Mk.II":102,
	"Carpet Bomber Mk.II":104,
	"Masked Mender Mk.II":105,
	"Woodland Warrior Mk.II":106,
	"Forest Fire Mk.II":109,
	"Backwoods Boomstick Mk.II":112,
	"Woodsy Widowmaker Mk.II":113,
	"Night Owl Mk.II":114,
	"Iron Wood Mk.II":120,
	"Plaid Potshotter Mk.II":122,
	"Bovine Blazemaker Mk.II":130,
	"Civil Servant Mk.II":139,
	"Smalltown Bringdown Mk.II":143,
	"Civic Duty Mk.II":144,
	"Dead Reckoner Mk.II":151,
	"Autumn Mk.II":160,
	"Nutcracker Mk.II":161,
	"Macabre Web Mk.II":163,
	"Bloom Buffed":200,
	"Quack Canvassed":201,
	"Bank Rolled":202,
	"Merc Stained":203,
	"Kill Covered":204,
	"Fire Glazed":205,
	"Pizza Polished":206,
	"Bonk Varnished":207,
	"Star Crossed":208,
	"Clover Camo'd":209,
	"Freedom Wrapped":210,
	"Cardboard Boxed":211,
	"Dream Piped":212,
	"Miami Element":213,
	"Neo Tokyo":214,
	"Geometrical Teams":215,
	"Bomber Soul":217,
	"Uranium":218,
	"Cabin Fevered":220,
	"Polar Surprise":221,
	"Hana":223,
	"Dovetailed":224,
	"Cosmic Calamity":225,
	"Hazard Warning":226,
	"Mosaic":228,
	"Jazzy":230,
	"Alien Tech":232,
	"Damascus & Mahogany":234,
	"Skull Study":235,
	"Haunted Ghosts":236,
	"Spectral Shimmered":237,
	"Spirit of Halloween":238,
	"Horror Holiday":239,
	"Totally Boned":240,
	"Electroshocked":241,
	"Ghost Town":242,
	"Tumor Toasted":243,
	"Calavera Canvas":244,
	"Snow Covered":245,
	"Frost Ornamented":246,
	"Smissmas Village":247,
	"Igloo":248,
	"Seriously Snowed":249,
	"Smissmas Camo":250,
	"Sleighin' Style":251,
	"Alpine":252,
	"Gift Wrapped":253,
	"Winterland Wrapped":254,
	"Yeti Coated":300,
	"Park Pigmented":301,
	"Mannana Peeled":302,
	"Macaw Masked":303,
	"Sax Waxed":304,
	"Anodized Aloha":305,
	"Bamboo Brushed":306,
	"Tiger Buffed":307,
	"Croc Dusted":308,
	"Piña Polished":309,
	"Leopard Printed":310,
	"Dragon Slayer":390,
	"Smissmas Sweater":391,

	"Red Rock Roscoe":0,
	"Sand Cannon":1,
	"Wrapped Reviver":2,
	"Psychedelic Slugger":3,
	"Carpet Bomber":4,
	"Masked Mender":5,
	"Woodland Warrior":6,
	"Purple Range":7,
	"Sudden Flurry":8,
	"Forest Fire":9,
	"King of the Jungle":10,
	"Night Terror":11,
	"Backwoods Boomstick":12,
	"Woodsy Widowmaker":13,
	"Night Owl":14,
	"Tartan Torpedo":15,
	"Rustic Ruiner":16,
	"Barn Burner":17,
	"Homemade Heater":18,
	"Lumber From Down Under":19,
	"Iron Wood":20,
	"Country Crusher":21,
	"Plaid Potshotter":22,
	"Shot in the Dark":23,
	"Blasted Bombardier":24,
	"Reclaimed Reanimator":25,
	"Antique Annihilator":26,
	"Old Country":27,
	"American Pastoral":28,
	"Backcountry Blaster":29,
	"Bovine Blazemaker":30,
	"War Room":31,
	"Treadplate Tormenter":32,
	"Bogtrotter":33,
	"Earth, Sky and Fire":34,
	"Hickory Hole-Puncher":35,
	"Spruce Deuce":36,
	"Team Sprayer":37,
	"Rooftop Wrangler":38,
	"Civil Servant":39,
	"Citizen Pain":40,
	"Local Hero":41,
	"Mayor":42,
	"Smalltown Bringdown":43,
	"Civic Duty":44,
	"Liquid Asset":45,
	"Black Dahlia":46,
	"Lightning Rod":47,
	"Pink Elephant":48,
	"Flash Fryer":49,
	"Spark of Life":50,
	"Dead Reckoner":51,
	"Shell Shocker":52,
	"Current Event":53,
	"Turbine Torcher":54,
	"Brick House":55,
	"Sandstone Special":56,
	"Aqua Marine":57,
	"Low Profile":58,
	"Thunderbolt":59,
	"Autumn":60,
	"Nutcracker":61,
	"Pumpkin Patch":62,
	"Macabre Web":63,
	"Boneyard":64,
	"Wildwood":65,
	"Balloonicorn":66,
	"Rainbow":91,
	"Sweet Dreams":68,
	"Blue Mew":69,
	"Brain Candy":70,
	"Stabbed to Hell":71,
	"Flower Power":72,
	"Mister Cuddles":73,
	"Shot to Hell":74,
	"Torqued to Hell":75,
	"Coffin Nail":93,
	"Top Shelf":77,
	"Dressed to Kill":78,
	"High Roller's":79,
	"Warhawk":80,
	"Blitzkrieg":81,
	"Airwolf":82,
	"Corsair":83,
	"Butcher Bird":84,
	"Killer Bee":92,
	"Red Bear":86
}

exports.wears = [
	"(Factory New)",
	"(Minimal Wear)",
	"(Field-Tested)",
	"(Well-Worn)",
	"(Battle Scarred)"
]

exports.wear = {
	"(Factory New)":1,
	"(Minimal Wear)":2,
	"(Field-Tested)":3,
	"(Well-Worn)":4,
	"(Battle Scarred)":5
}