// Make a node module for this that can be used for any related project
exports.qualities = [
	'Normal',
	'Genuine',
	'Vintage',
	'rarity3',
	'Unusual',
	'Unique',
	'Community',
	'Valve',
	'Self-Made',
	'Customized',
	'Strange',
	'Completed',
	'Haunted',
	'Collector\'s',
	'Decorated Weapon'
];

exports.quality = {
	'Normal': 0,
	'Genuine': 1,
	'Vintage': 3,
	'rarity3': 4,
	'Unusual': 5,
	'Unique': 6,
	'Community': 7,
	'Valve': 8,
	'Self-Made': 9,
	'Customized': 10,
	'Strange': 11,
	'Completed': 12,
	'Haunted': 13,
	'Collector\'s': 14,
	'Decorated Weapon': 15,
	'0': 'Normal',
	'1': 'Genuine',
	'3': 'Vintage',
	'4': 'rarity3',
	'5': 'Unusual',
	'6': 'Unique',
	'7': 'Community',
	'8': 'Valve',
	'9': 'Self-Made',
	'10': 'Customized',
	'11': 'Strange',
	'12': 'Completed',
	'13': 'Haunted',
	'14': 'Collector\'s',
	'15': 'Decorated Weapon'
};

exports.killstreaks = [
	'Professional Killstreak',
	'Specialized Killstreak',
	'Killstreak'
];

exports.killstreak = {
	'Professional Killstreak': 3,
	'Specialized Killstreak': 2,
	'Killstreak': 1,
	'3': 'Professional Killstreak',
	'2': 'Specialized Killstreak',
	'1': 'Killstreak'
};

exports.effects = [
	'Flying Bits',
	'Nemesis Burst',
	'Holy Glow',
	'Green Confetti',
	'Purple Confetti',
	'Haunted Ghosts',
	'Green Energy',
	'Purple Energy',
	'Circling TF Logo',
	'Massed Flies',
	'Burning Flames',
	'Scorching Flames',
	'Searing Plasma',
	'Vivid Plasma',
	'Sunbeams',
	'Circling Peace Sign',
	'Circling Heart',
	'Stormy Storm',
	'Blizzardy Storm',
	'Nuts n\' Bolts',
	'Orbiting Planets',
	'Eerie Orbiting Fire',
	'Orbiting Fire',
	'Bubbling',
	'Smoking',
	'Steaming',
	'Flaming Lantern',
	'Cloudy Moon',
	'Cauldron Bubbles',
	'Knifestorm',
	'Misty Skull',
	'Harvest Moon',
	'It\'s A Secret To Everybody',
	'Stormy 13th Hour',
	'Kill-a-Watt',
	'Terror-Watt',
	'Cloud 9',
	'Aces High',
	'Dead Presidents',
	'Miami Nights',
	'Disco Beat Down',
	'Phosphorous',
	'Sulphurous',
	'Memory Leak',
	'Overclocked',
	'Electrostatic',
	'Power Surge',
	'Anti-Freeze',
	'Time Warp',
	'Green Black Hole',
	'Roboactive',
	'Arcana',
	'Spellbound',
	'Chiroptera Venenata',
	'Poisoned Shadows',
	'Something Burning This Way Comes',
	'Hellfire',
	'Darkblaze',
	'Demonflame',
	'Bonzo The All-Gnawing',
	'Amaranthine',
	'Stare From Beyond',
	'The Ooze',
	'Ghastly Ghosts Jr',
	'Haunted Phantasm Jr',
	'Frostbite',
	'Molten Mallard',
	'Morning Glory',
	'Death at Dusk',
	'Abduction',
	'Atomic',
	'Subatomic',
	'Electric Hat Protector',
	'Magnetic Hat Protector',
	'Voltaic Hat Protector',
	'Galactic Codex',
	'Ancient Codex',
	'Nebula',
	'Death by Disco',
	'It\'s a mystery to everyone',
	'It\'s a puzzle to me',
	'Ether Trail',
	'Nether Trail',
	'Ancient Eldritch',
	'Eldritch Flame',
	'Neutron Star',
	'Tesla Coil',
	'Starstorm Insomnia',
	'Starstorm Slumber',
	'Brain Drain',
	'Open Mind',
	'Head of Steam',
	'The Galactic Gateway',
	'The Eldritch Opening',
	'The Dark Doorway',
	'Ring of Fire',
	'Vicious Circle',
	'White Lightning',
	'Omniscient Orb',
	'Clairvoyance',
	'Fifth Dimension',
	'Vicious Vortex',
	'Menacing Miasma',
	'Abyssal Aura',
	'Wicked Wood',
	'Ghastly Grove',
	'Mystical Medley',
	'Ethereal Essence',
	'Twisted Radiance',
	'Violet Vortex',
	'Verdant Vortex',
	'Valiant Vortex',
	'Sparkling Lights',
	'Frozen Icefall',
	'Fragmented Gluons',
	'Fragmented Quarks',
	'Fragmented Photons',
	'Defragmenting Reality',
	'Fragmenting Reality',
	'Refragmenting Reality',
	'Snowfallen',
	'Snowblinded',
	'Pyroland Daydream',
	'Verdatica',
	'Aromatica',
	'Chromatica',
	'Prismatica',
	'Bee Swarm',
	'Frisky Fireflies',
	'Smoldering Spirits',
	'Wandering Wisps',
	'Kaleidoscope',
	'Green Giggler',
	'Laugh-O-Lantern',
	'Plum Prankster',
	'Pyroland Nightmare',
	'Gravelly Ghoul',
	'Vexed Volcanics',
	'Gourdian Angel',
	'Pumpkin Party',
	'Hot',
	'Isotope',
	'Cool',
	'Energy Orb',
	'Showstopper',
	'Holy Grail',
	'\'72',
	'Fountain of Delight',
	'Screaming Tiger',
	'Skill Gotten Gains',
	'Midnight Whirlwind',
	'Silver Cyclone',
	'Mega Strike',
	'Haunted Phantasm',
	'Ghastly Ghosts',
	'Hellish Inferno',
	'Spectral Swirl',
	'Infernal Flames',
	'Infernal Smoke',
	'Acidic Bubbles of Envy',
	'Flammable Bubbles of Attraction',
	'Poisonous Bubbles of Regret',
	'Roaring Rockets',
	'Spooky Night',
	'Ominous Night',
	'Bewitched',
	'Accursed',
	'Enchanted',
	'Static Mist',
	'Eerie Lightning',
	'Terrifying Thunder',
	'Jarate Shock',
	'Nether Void',
	'Good-Hearted Goodies',
	'Wintery Wisp',
	'Arctic Aurora',
	'Winter Spirit',
	'Festive Spirit',
	'Magical Spirit',
	'Spectral Escort',
	'Astral Presence',
	'Arcane Assistance',
	'Emerald Allurement',
	'Pyrophoric Personality',
	'Spellbound Aspect',
	'Static Shock',
	'Veno Shock',
	'Toxic Terrors',
	'Arachnid Assault',
	'Creepy Crawlies'
];

exports.effect = {
	'Particle 1': 1,
	'Flying Bits': 2,
	'Nemesis Burst': 3,
	'Community Sparkle': 4,
	'Holy Glow': 5,
	'Green Confetti': 6,
	'Purple Confetti': 7,
	'Haunted Ghosts': 8,
	'Green Energy': 9,
	'Purple Energy': 10,
	'Circling TF Logo': 11,
	'Massed Flies': 12,
	'Burning Flames': 13,
	'Scorching Flames': 14,
	'Searing Plasma': 15,
	'Vivid Plasma': 16,
	'Sunbeams': 17,
	'Circling Peace Sign': 18,
	'Circling Heart': 19,
	'Map Stamps': 20,
	'Genteel Smoke': 28,
	'Stormy Storm': 29,
	'Blizzardy Storm': 30,
	'Nuts n\' Bolts': 31,
	'Orbiting Planets': 32,
	'Orbiting Fire': 33,
	'Bubbling': 34,
	'Smoking': 35,
	'Steaming': 36,
	'Flaming Lantern': 37,
	'Cloudy Moon': 38,
	'Cauldron Bubbles': 39,
	'Eerie Orbiting Fire': 40,
	'Knifestorm': 43,
	'Misty Skull': 44,
	'Harvest Moon': 45,
	'It\'s A Secret To Everybody': 46,
	'Stormy 13th Hour': 47,
	'Attrib_Particle55': 55,
	'Kill-a-Watt': 56,
	'Terror-Watt': 57,
	'Cloud 9': 58,
	'Aces High': 59,
	'Dead Presidents': 60,
	'Miami Nights': 61,
	'Disco Beat Down': 62,
	'Phosphorous': 63,
	'Sulphurous': 64,
	'Memory Leak': 65,
	'Overclocked': 66,
	'Electrostatic': 67,
	'Power Surge': 68,
	'Anti-Freeze': 69,
	'Time Warp': 70,
	'Green Black Hole': 71,
	'Roboactive': 72,
	'Arcana': 73,
	'Spellbound': 74,
	'Chiroptera Venenata': 75,
	'Poisoned Shadows': 76,
	'Something Burning This Way Comes': 77,
	'Hellfire': 78,
	'Darkblaze': 79,
	'Demonflame': 80,
	'Bonzo The All-Gnawing': 81,
	'Amaranthine': 82,
	'Stare From Beyond': 83,
	'The Ooze': 84,
	'Ghastly Ghosts Jr': 85,
	'Haunted Phantasm Jr': 86,
	'Frostbite': 87,
	'Molten Mallard': 88,
	'Morning Glory': 89,
	'Death at Dusk': 90,
	'Abduction': 91,
	'Atomic': 92,
	'Subatomic': 93,
	'Electric Hat Protector': 94,
	'Magnetic Hat Protector': 95,
	'Voltaic Hat Protector': 96,
	'Galactic Codex': 97,
	'Ancient Codex': 98,
	'Nebula': 99,
	'Death by Disco': 100,
	'It\'s a mystery to everyone': 101,
	'It\'s a puzzle to me': 102,
	'Ether Trail': 103,
	'Nether Trail': 104,
	'Ancient Eldritch': 105,
	'Eldritch Flame': 106,
	'Neutron Star': 107,
	'Tesla Coil': 108,
	'Starstorm Insomnia': 109,
	'Starstorm Slumber': 110,
	'Brain Drain': 111,
	'Open Mind': 112,
	'Head of Steam': 113,
	'The Galactic Gateway': 114,
	'The Eldritch Opening': 115,
	'The Dark Doorway': 116,
	'Ring of Fire': 117,
	'Vicious Circle': 118,
	'White Lightning': 119,
	'Omniscient Orb': 120,
	'Clairvoyance': 121,
	'Fifth Dimension': 122,
	'Vicious Vortex': 123,
	'Menacing Miasma': 124,
	'Abyssal Aura': 125,
	'Wicked Wood': 126,
	'Ghastly Grove': 127,
	'Mystical Medley': 128,
	'Ethereal Essence': 129,
	'Twisted Radiance': 130,
	'Violet Vortex': 131,
	'Verdant Vortex': 132,
	'Valiant Vortex': 133,
	'Sparkling Lights': 134,
	'Frozen Icefall': 135,
	'Fragmented Gluons': 136,
	'Fragmented Quarks': 137,
	'Fragmented Photons': 138,
	'Defragmenting Reality': 139,
	'Fragmenting Reality': 141,
	'Refragmenting Reality': 142,
	'Snowfallen': 143,
	'Snowblinded': 144,
	'Pyroland Daydream': 145,
	'Verdatica': 147,
	'Aromatica': 148,
	'Chromatica': 149,
	'Prismatica': 150,
	'Bee Swarm': 151,
	'Frisky Fireflies': 152,
	'Smoldering Spirits': 153,
	'Wandering Wisps': 154,
	'Kaleidoscope': 155,
	'Green Giggler': 156,
	'Laugh-O-Lantern': 157,
	'Plum Prankster': 158,
	'Pyroland Nightmare': 159,
	'Gravelly Ghoul': 160,
	'Vexed Volcanics': 161,
	'Gourdian Angel': 162,
	'Pumpkin Party': 163,
	'Hot': 701,
	'Isotope': 702,
	'Cool': 703,
	'Energy Orb': 704,
	'Attrib_Particle2001': 2001,
	'Attrib_Particle2002': 2002,
	'Attrib_Particle2003': 2003,
	'Attrib_Particle2004': 2004,
	'Attrib_Particle2005': 2005,
	'Attrib_Particle2006': 2006,
	'Attrib_Particle2007': 2007,
	'Attrib_Particle2008': 2008,
	'Showstopper': 3001,
	'Holy Grail': 3003,
	'\'72': 3004,
	'Fountain of Delight': 3005,
	'Screaming Tiger': 3006,
	'Skill Gotten Gains': 3007,
	'Midnight Whirlwind': 3008,
	'Silver Cyclone': 3009,
	'Mega Strike': 3010,
	'Haunted Phantasm': 3011,
	'Ghastly Ghosts': 3012,
	'Hellish Inferno': 3013,
	'Spectral Swirl': 3014,
	'Infernal Flames': 3015,
	'Infernal Smoke': 3016,
	'Acidic Bubbles of Envy': 3017,
	'Flammable Bubbles of Attraction': 3018,
	'Poisonous Bubbles of Regret': 3019,
	'Roaring Rockets': 3020,
	'Spooky Night': 3021,
	'Ominous Night': 3022,
	'Bewitched': 3023,
	'Accursed': 3024,
	'Enchanted': 3025,
	'Static Mist': 3026,
	'Eerie Lightning': 3027,
	'Terrifying Thunder': 3028,
	'Jarate Shock': 3029,
	'Nether Void': 3030,
	'Good-Hearted Goodies': 3031,
	'Wintery Wisp': 3032,
	'Arctic Aurora': 3033,
	'Winter Spirit': 3034,
	'Festive Spirit': 3035,
	'Magical Spirit': 3036,
	'Spectral Escort': 3037,
	'Astral Presence': 3038,
	'Arcane Assistance': 3039,
	'Emerald Allurement': 3041,
	'Pyrophoric Personality': 3042,
	'Spellbound Aspect': 3043,
	'Static Shock': 3044,
	'Veno Shock': 3045,
	'Toxic Terrors': 3046,
	'Arachnid Assault': 3047,
	'Creepy Crawlies': 3048,
	'Attrib_Particle22001': 22001,
	'Attrib_Particle22002': 22002,
	'Attrib_Particle22003': 22003,
	'Attrib_Particle22004': 22004,
	'Attrib_Particle22005': 22005,
	'Attrib_Particle22006': 22006,
	'Attrib_Particle22007': 22007,
	'Attrib_Particle22008': 22008,

	'1': 'Particle 1',
	'2': 'Flying Bits',
	'3': 'Nemesis Burst',
	'4': 'Community Sparkle',
	'5': 'Holy Glow',
	'6': 'Green Confetti',
	'7': 'Purple Confetti',
	'8': 'Haunted Ghosts',
	'9': 'Green Energy',
	'10': 'Purple Energy',
	'11': 'Circling TF Logo',
	'12': 'Massed Flies',
	'13': 'Burning Flames',
	'14': 'Scorching Flames',
	'15': 'Searing Plasma',
	'16': 'Vivid Plasma',
	'17': 'Sunbeams',
	'18': 'Circling Peace Sign',
	'19': 'Circling Heart',
	'20': 'Map Stamps',
	'28': 'Genteel Smoke',
	'29': 'Stormy Storm',
	'30': 'Blizzardy Storm',
	'31': 'Nuts n\' Bolts',
	'32': 'Orbiting Planets',
	'33': 'Orbiting Fire',
	'34': 'Bubbling',
	'35': 'Smoking',
	'36': 'Steaming',
	'37': 'Flaming Lantern',
	'38': 'Cloudy Moon',
	'39': 'Cauldron Bubbles',
	'40': 'Eerie Orbiting Fire',
	'43': 'Knifestorm',
	'44': 'Misty Skull',
	'45': 'Harvest Moon',
	'46': 'It\'s A Secret To Everybody',
	'47': 'Stormy 13th Hour',
	'55': 'Attrib_Particle55',
	'56': 'Kill-a-Watt',
	'57': 'Terror-Watt',
	'58': 'Cloud 9',
	'59': 'Aces High',
	'60': 'Dead Presidents',
	'61': 'Miami Nights',
	'62': 'Disco Beat Down',
	'63': 'Phosphorous',
	'64': 'Sulphurous',
	'65': 'Memory Leak',
	'66': 'Overclocked',
	'67': 'Electrostatic',
	'68': 'Power Surge',
	'69': 'Anti-Freeze',
	'70': 'Time Warp',
	'71': 'Green Black Hole',
	'72': 'Roboactive',
	'73': 'Arcana',
	'74': 'Spellbound',
	'75': 'Chiroptera Venenata',
	'76': 'Poisoned Shadows',
	'77': 'Something Burning This Way Comes',
	'78': 'Hellfire',
	'79': 'Darkblaze',
	'80': 'Demonflame',
	'81': 'Bonzo The All-Gnawing',
	'82': 'Amaranthine',
	'83': 'Stare From Beyond',
	'84': 'The Ooze',
	'85': 'Ghastly Ghosts Jr',
	'86': 'Haunted Phantasm Jr',
	'87': 'Frostbite',
	'88': 'Molten Mallard',
	'89': 'Morning Glory',
	'90': 'Death at Dusk',
	'91': 'Abduction',
	'92': 'Atomic',
	'93': 'Subatomic',
	'94': 'Electric Hat Protector',
	'95': 'Magnetic Hat Protector',
	'96': 'Voltaic Hat Protector',
	'97': 'Galactic Codex',
	'98': 'Ancient Codex',
	'99': 'Nebula',
	'100': 'Death by Disco',
	'101': 'It\'s a mystery to everyone',
	'102': 'It\'s a puzzle to me',
	'103': 'Ether Trail',
	'104': 'Nether Trail',
	'105': 'Ancient Eldritch',
	'106': 'Eldritch Flame',
	'107': 'Neutron Star',
	'108': 'Tesla Coil',
	'109': 'Starstorm Insomnia',
	'110': 'Starstorm Slumber',
	'111': 'Brain Drain',
	'112': 'Open Mind',
	'113': 'Head of Steam',
	'114': 'The Galactic Gateway',
	'115': 'The Eldritch Opening',
	'116': 'The Dark Doorway',
	'117': 'Ring of Fire',
	'118': 'Vicious Circle',
	'119': 'White Lightning',
	'120': 'Omniscient Orb',
	'121': 'Clairvoyance',
	'122': 'Fifth Dimension',
	'123': 'Vicious Vortex',
	'124': 'Menacing Miasma',
	'125': 'Abyssal Aura',
	'126': 'Wicked Wood',
	'127': 'Ghastly Grove',
	'128': 'Mystical Medley',
	'129': 'Ethereal Essence',
	'130': 'Twisted Radiance',
	'131': 'Violet Vortex',
	'132': 'Verdant Vortex',
	'133': 'Valiant Vortex',
	'134': 'Sparkling Lights',
	'135': 'Frozen Icefall',
	'136': 'Fragmented Gluons',
	'137': 'Fragmented Quarks',
	'138': 'Fragmented Photons',
	'139': 'Defragmenting Reality',
	'141': 'Fragmenting Reality',
	'142': 'Refragmenting Reality',
	'143': 'Snowfallen',
	'144': 'Snowblinded',
	'145': 'Pyroland Daydream',
	'147': 'Verdatica',
	'148': 'Aromatica',
	'149': 'Chromatica',
	'150': 'Prismatica',
	'151': 'Bee Swarm',
	'152': 'Frisky Fireflies',
	'153': 'Smoldering Spirits',
	'154': 'Wandering Wisps',
	'155': 'Kaleidoscope',
	'156': 'Green Giggler',
	'157': 'Laugh-O-Lantern',
	'158': 'Plum Prankster',
	'159': 'Pyroland Nightmare',
	'160': 'Gravelly Ghoul',
	'161': 'Vexed Volcanics',
	'162': 'Gourdian Angel',
	'163': 'Pumpkin Party',
	'701': 'Hot',
	'702': 'Isotope',
	'703': 'Cool',
	'704': 'Energy Orb',
	'2001': 'Attrib_Particle2001',
	'2002': 'Attrib_Particle2002',
	'2003': 'Attrib_Particle2003',
	'2004': 'Attrib_Particle2004',
	'2005': 'Attrib_Particle2005',
	'2006': 'Attrib_Particle2006',
	'2007': 'Attrib_Particle2007',
	'2008': 'Attrib_Particle2008',
	'3001': 'Showstopper',
	'3003': 'Holy Grail',
	'3004': '\'72',
	'3005': 'Fountain of Delight',
	'3006': 'Screaming Tiger',
	'3007': 'Skill Gotten Gains',
	'3008': 'Midnight Whirlwind',
	'3009': 'Silver Cyclone',
	'3010': 'Mega Strike',
	'3011': 'Haunted Phantasm',
	'3012': 'Ghastly Ghosts',
	'3013': 'Hellish Inferno',
	'3014': 'Spectral Swirl',
	'3015': 'Infernal Flames',
	'3016': 'Infernal Smoke',
	'3017': 'Acidic Bubbles of Envy',
	'3018': 'Flammable Bubbles of Attraction',
	'3019': 'Poisonous Bubbles of Regret',
	'3020': 'Roaring Rockets',
	'3021': 'Spooky Night',
	'3022': 'Ominous Night',
	'3023': 'Bewitched',
	'3024': 'Accursed',
	'3025': 'Enchanted',
	'3026': 'Static Mist',
	'3027': 'Eerie Lightning',
	'3028': 'Terrifying Thunder',
	'3029': 'Jarate Shock',
	'3030': 'Nether Void',
	'3031': 'Good-Hearted Goodies',
	'3032': 'Wintery Wisp',
	'3033': 'Arctic Aurora',
	'3034': 'Winter Spirit',
	'3035': 'Festive Spirit',
	'3036': 'Magical Spirit',
	'3037': 'Spectral Escort',
	'3038': 'Astral Presence',
	'3039': 'Arcane Assistance',
	'3041': 'Emerald Allurement',
	'3042': 'Pyrophoric Personality',
	'3043': 'Spellbound Aspect',
	'3044': 'Static Shock',
	'3045': 'Veno Shock',
	'3046': 'Toxic Terrors',
	'3047': 'Arachnid Assault',
	'3048': 'Creepy Crawlies',
	'22001': 'Attrib_Particle22001',
	'22002': 'Attrib_Particle22002',
	'22003': 'Attrib_Particle22003',
	'22004': 'Attrib_Particle22004',
	'22005': 'Attrib_Particle22005',
	'22006': 'Attrib_Particle22006',
	'22007': 'Attrib_Particle22007',
	'22008': 'Attrib_Particle22008'
};

exports.skins = [
	// War paints first because of Mk.II and stuffs
	'Wrapped Reviver Mk.II',
	'Carpet Bomber Mk.II',
	'Masked Mender Mk.II',
	'Woodland Warrior Mk.II',
	'Forest Fire Mk.II',
	'Backwoods Boomstick Mk.II',
	'Woodsy Widowmaker Mk.II',
	'Night Owl Mk.II',
	'Iron Wood Mk.II',
	'Plaid Potshotter Mk.II',
	'Bovine Blazemaker Mk.II',
	'Civil Servant Mk.II',
	'Smalltown Bringdown Mk.II',
	'Civic Duty Mk.II',
	'Dead Reckoner Mk.II',
	'Autumn Mk.II',
	'Nutcracker Mk.II',
	'Macabre Web Mk.II',
	'Bloom Buffed',
	'Quack Canvassed',
	'Bank Rolled',
	'Merc Stained',
	'Kill Covered',
	'Fire Glazed',
	'Pizza Polished',
	'Bonk Varnished',
	'Star Crossed',
	'Clover Camo\'d',
	'Freedom Wrapped',
	'Cardboard Boxed',
	'Dream Piped',
	'Miami Element',
	'Neo Tokyo',
	'Geometrical Teams',
	'Bomber Soul',
	'Uranium',
	'Cabin Fevered',
	'Polar Surprise',
	'Hana',
	'Dovetailed',
	'Cosmic Calamity',
	'Hazard Warning',
	'Mosaic',
	'Jazzy',
	'Alien Tech',
	'Damascus & Mahogany',
	'Skull Study',
	'Haunted Ghosts',
	'Spectral Shimmered',
	'Spirit of Halloween',
	'Horror Holiday',
	'Totally Boned',
	'Electroshocked',
	'Ghost Town',
	'Tumor Toasted',
	'Calavera Canvas',
	'Snow Covered',
	'Frost Ornamented',
	'Smissmas Village',
	'Igloo',
	'Seriously Snowed',
	'Smissmas Camo',
	'Sleighin\' Style',
	'Alpine',
	'Gift Wrapped',
	'Winterland Wrapped',
	'Yeti Coated',
	'Park Pigmented',
	'Mannana Peeled',
	'Macaw Masked',
	'Sax Waxed',
	'Anodized Aloha',
	'Bamboo Brushed',
	'Tiger Buffed',
	'Croc Dusted',
	'Piña Polished',
	'Leopard Printed',
	'Dragon Slayer',
	'Smissmas Sweater',

	// Non war paints
	'Red Rock Roscoe',
	'Sand Cannon',
	'Wrapped Reviver',
	'Psychedelic Slugger',
	'Carpet Bomber',
	'Masked Mender',
	'Woodland Warrior',
	'Purple Range',
	'Sudden Flurry',
	'Forest Fire',
	'King of the Jungle',
	'Night Terror',
	'Backwoods Boomstick',
	'Woodsy Widowmaker',
	'Night Owl',
	'Tartan Torpedo',
	'Rustic Ruiner',
	'Barn Burner',
	'Homemade Heater',
	'Lumber From Down Under',
	'Iron Wood',
	'Country Crusher',
	'Plaid Potshotter',
	'Shot in the Dark',
	'Blasted Bombardier',
	'Reclaimed Reanimator',
	'Antique Annihilator',
	'Old Country',
	'American Pastoral',
	'Backcountry Blaster',
	'Bovine Blazemaker',
	'War Room',
	'Treadplate Tormenter',
	'Bogtrotter',
	'Earth, Sky and Fire',
	'Hickory Hole-Puncher',
	'Spruce Deuce',
	'Team Sprayer',
	'Rooftop Wrangler',
	'Civil Servant',
	'Citizen Pain',
	'Local Hero',
	'Mayor',
	'Smalltown Bringdown',
	'Civic Duty',
	'Liquid Asset',
	'Black Dahlia',
	'Lightning Rod',
	'Pink Elephant',
	'Flash Fryer',
	'Spark of Life',
	'Dead Reckoner',
	'Shell Shocker',
	'Current Event',
	'Turbine Torcher',
	'Brick House',
	'Sandstone Special',
	'Aqua Marine',
	'Low Profile',
	'Thunderbolt',
	'Autumn',
	'Nutcracker',
	'Pumpkin Patch',
	'Macabre Web',
	'Boneyard',
	'Wildwood',
	'Balloonicorn',
	'Rainbow',
	'Sweet Dreams',
	'Blue Mew',
	'Brain Candy',
	'Stabbed to Hell',
	'Flower Power',
	'Mister Cuddles',
	'Shot to Hell',
	'Torqued to Hell',
	'Coffin Nail',
	'Top Shelf',
	'Dressed to Kill',
	'High Roller\'s',
	'Warhawk',
	'Blitzkrieg',
	'Airwolf',
	'Corsair',
	'Butcher Bird',
	'Killer Bee',
	'Red Bear'
];

exports.skin = {
	'Wrapped Reviver Mk.II': 102,
	'Carpet Bomber Mk.II': 104,
	'Masked Mender Mk.II': 105,
	'Woodland Warrior Mk.II': 106,
	'Forest Fire Mk.II': 109,
	'Backwoods Boomstick Mk.II': 112,
	'Woodsy Widowmaker Mk.II': 113,
	'Night Owl Mk.II': 114,
	'Iron Wood Mk.II': 120,
	'Plaid Potshotter Mk.II': 122,
	'Bovine Blazemaker Mk.II': 130,
	'Civil Servant Mk.II': 139,
	'Smalltown Bringdown Mk.II': 143,
	'Civic Duty Mk.II': 144,
	'Dead Reckoner Mk.II': 151,
	'Autumn Mk.II': 160,
	'Nutcracker Mk.II': 161,
	'Macabre Web Mk.II': 163,
	'Bloom Buffed': 200,
	'Quack Canvassed': 201,
	'Bank Rolled': 202,
	'Merc Stained': 203,
	'Kill Covered': 204,
	'Fire Glazed': 205,
	'Pizza Polished': 206,
	'Bonk Varnished': 207,
	'Star Crossed': 208,
	'Clover Camo\'d': 209,
	'Freedom Wrapped': 210,
	'Cardboard Boxed': 211,
	'Dream Piped': 212,
	'Miami Element': 213,
	'Neo Tokyo': 214,
	'Geometrical Teams': 215,
	'Bomber Soul': 217,
	'Uranium': 218,
	'Cabin Fevered': 220,
	'Polar Surprise': 221,
	'Hana': 223,
	'Dovetailed': 224,
	'Cosmic Calamity': 225,
	'Hazard Warning': 226,
	'Mosaic': 228,
	'Jazzy': 230,
	'Alien Tech': 232,
	'Damascus & Mahogany': 234,
	'Skull Study': 235,
	'Haunted Ghosts': 236,
	'Spectral Shimmered': 237,
	'Spirit of Halloween': 238,
	'Horror Holiday': 239,
	'Totally Boned': 240,
	'Electroshocked': 241,
	'Ghost Town': 242,
	'Tumor Toasted': 243,
	'Calavera Canvas': 244,
	'Snow Covered': 245,
	'Frost Ornamented': 246,
	'Smissmas Village': 247,
	'Igloo': 248,
	'Seriously Snowed': 249,
	'Smissmas Camo': 250,
	'Sleighin\' Style': 251,
	'Alpine': 252,
	'Gift Wrapped': 253,
	'Winterland Wrapped': 254,
	'Yeti Coated': 300,
	'Park Pigmented': 301,
	'Mannana Peeled': 302,
	'Macaw Masked': 303,
	'Sax Waxed': 304,
	'Anodized Aloha': 305,
	'Bamboo Brushed': 306,
	'Tiger Buffed': 307,
	'Croc Dusted': 308,
	'Piña Polished': 309,
	'Leopard Printed': 310,
	'Dragon Slayer': 390,
	'Smissmas Sweater': 391,

	'Red Rock Roscoe': 0,
	'Sand Cannon': 1,
	'Wrapped Reviver': 2,
	'Psychedelic Slugger': 3,
	'Carpet Bomber': 4,
	'Masked Mender': 5,
	'Woodland Warrior': 6,
	'Purple Range': 7,
	'Sudden Flurry': 8,
	'Forest Fire': 9,
	'King of the Jungle': 10,
	'Night Terror': 11,
	'Backwoods Boomstick': 12,
	'Woodsy Widowmaker': 13,
	'Night Owl': 14,
	'Tartan Torpedo': 15,
	'Rustic Ruiner': 16,
	'Barn Burner': 17,
	'Homemade Heater': 18,
	'Lumber From Down Under': 19,
	'Iron Wood': 20,
	'Country Crusher': 21,
	'Plaid Potshotter': 22,
	'Shot in the Dark': 23,
	'Blasted Bombardier': 24,
	'Reclaimed Reanimator': 25,
	'Antique Annihilator': 26,
	'Old Country': 27,
	'American Pastoral': 28,
	'Backcountry Blaster': 29,
	'Bovine Blazemaker': 30,
	'War Room': 31,
	'Treadplate Tormenter': 32,
	'Bogtrotter': 33,
	'Earth, Sky and Fire': 34,
	'Hickory Hole-Puncher': 35,
	'Spruce Deuce': 36,
	'Team Sprayer': 37,
	'Rooftop Wrangler': 38,
	'Civil Servant': 39,
	'Citizen Pain': 40,
	'Local Hero': 41,
	'Mayor': 42,
	'Smalltown Bringdown': 43,
	'Civic Duty': 44,
	'Liquid Asset': 45,
	'Black Dahlia': 46,
	'Lightning Rod': 47,
	'Pink Elephant': 48,
	'Flash Fryer': 49,
	'Spark of Life': 50,
	'Dead Reckoner': 51,
	'Shell Shocker': 52,
	'Current Event': 53,
	'Turbine Torcher': 54,
	'Brick House': 55,
	'Sandstone Special': 56,
	'Aqua Marine': 57,
	'Low Profile': 58,
	'Thunderbolt': 59,
	'Autumn': 60,
	'Nutcracker': 61,
	'Pumpkin Patch': 62,
	'Macabre Web': 63,
	'Boneyard': 64,
	'Wildwood': 65,
	'Balloonicorn': 66,
	'Rainbow': 91,
	'Sweet Dreams': 68,
	'Blue Mew': 69,
	'Brain Candy': 70,
	'Stabbed to Hell': 71,
	'Flower Power': 72,
	'Mister Cuddles': 73,
	'Shot to Hell': 74,
	'Torqued to Hell': 75,
	'Coffin Nail': 93,
	'Top Shelf': 77,
	'Dressed to Kill': 78,
	'High Roller\'s': 79,
	'Warhawk': 80,
	'Blitzkrieg': 81,
	'Airwolf': 82,
	'Corsair': 83,
	'Butcher Bird': 84,
	'Killer Bee': 92,
	'Red Bear': 86,

	'0': 'Red Rock Roscoe',
	'1': 'Sand Cannon',
	'2': 'Wrapped Reviver',
	'3': 'Psychedelic Slugger',
	'4': 'Carpet Bomber',
	'5': 'Masked Mender',
	'6': 'Woodland Warrior',
	'7': 'Purple Range',
	'8': 'Sudden Flurry',
	'9': 'Forest Fire',
	'10': 'King of the Jungle',
	'11': 'Night Terror',
	'12': 'Backwoods Boomstick',
	'13': 'Woodsy Widowmaker',
	'14': 'Night Owl',
	'15': 'Tartan Torpedo',
	'16': 'Rustic Ruiner',
	'17': 'Barn Burner',
	'18': 'Homemade Heater',
	'19': 'Lumber From Down Under',
	'20': 'Iron Wood',
	'21': 'Country Crusher',
	'22': 'Plaid Potshotter',
	'23': 'Shot in the Dark',
	'24': 'Blasted Bombardier',
	'25': 'Reclaimed Reanimator',
	'26': 'Antique Annihilator',
	'27': 'Old Country',
	'28': 'American Pastoral',
	'29': 'Backcountry Blaster',
	'30': 'Bovine Blazemaker',
	'31': 'War Room',
	'32': 'Treadplate Tormenter',
	'33': 'Bogtrotter',
	'34': 'Earth, Sky and Fire',
	'35': 'Hickory Hole-Puncher',
	'36': 'Spruce Deuce',
	'37': 'Team Sprayer',
	'38': 'Rooftop Wrangler',
	'39': 'Civil Servant',
	'40': 'Citizen Pain',
	'41': 'Local Hero',
	'42': 'Mayor',
	'43': 'Smalltown Bringdown',
	'44': 'Civic Duty',
	'45': 'Liquid Asset',
	'46': 'Black Dahlia',
	'47': 'Lightning Rod',
	'48': 'Pink Elephant',
	'49': 'Flash Fryer',
	'50': 'Spark of Life',
	'51': 'Dead Reckoner',
	'52': 'Shell Shocker',
	'53': 'Current Event',
	'54': 'Turbine Torcher',
	'55': 'Brick House',
	'56': 'Sandstone Special',
	'57': 'Aqua Marine',
	'58': 'Low Profile',
	'59': 'Thunderbolt',
	'60': 'Autumn',
	'61': 'Nutcracker',
	'62': 'Pumpkin Patch',
	'63': 'Macabre Web',
	'64': 'Boneyard',
	'65': 'Wildwood',
	'66': 'Balloonicorn',
	'68': 'Sweet Dreams',
	'69': 'Blue Mew',
	'70': 'Brain Candy',
	'71': 'Stabbed to Hell',
	'72': 'Flower Power',
	'73': 'Mister Cuddles',
	'74': 'Shot to Hell',
	'75': 'Torqued to Hell',
	'77': 'Top Shelf',
	'78': 'Dressed to Kill',
	'79': 'High Roller\'s',
	'80': 'Warhawk',
	'81': 'Blitzkrieg',
	'82': 'Airwolf',
	'83': 'Corsair',
	'84': 'Butcher Bird',
	'86': 'Red Bear',
	'91': 'Rainbow',
	'92': 'Killer Bee',
	'93': 'Coffin Nail',
	'102': 'Wrapped Reviver Mk.II',
	'104': 'Carpet Bomber Mk.II',
	'105': 'Masked Mender Mk.II',
	'106': 'Woodland Warrior Mk.II',
	'109': 'Forest Fire Mk.II',
	'112': 'Backwoods Boomstick Mk.II',
	'113': 'Woodsy Widowmaker Mk.II',
	'114': 'Night Owl Mk.II',
	'120': 'Iron Wood Mk.II',
	'122': 'Plaid Potshotter Mk.II',
	'130': 'Bovine Blazemaker Mk.II',
	'139': 'Civil Servant Mk.II',
	'143': 'Smalltown Bringdown Mk.II',
	'144': 'Civic Duty Mk.II',
	'151': 'Dead Reckoner Mk.II',
	'160': 'Autumn Mk.II',
	'161': 'Nutcracker Mk.II',
	'163': 'Macabre Web Mk.II',
	'200': 'Bloom Buffed',
	'201': 'Quack Canvassed',
	'202': 'Bank Rolled',
	'203': 'Merc Stained',
	'204': 'Kill Covered',
	'205': 'Fire Glazed',
	'206': 'Pizza Polished',
	'207': 'Bonk Varnished',
	'208': 'Star Crossed',
	'209': 'Clover Camo\'d',
	'210': 'Freedom Wrapped',
	'211': 'Cardboard Boxed',
	'212': 'Dream Piped',
	'213': 'Miami Element',
	'214': 'Neo Tokyo',
	'215': 'Geometrical Teams',
	'217': 'Bomber Soul',
	'218': 'Uranium',
	'220': 'Cabin Fevered',
	'221': 'Polar Surprise',
	'223': 'Hana',
	'224': 'Dovetailed',
	'225': 'Cosmic Calamity',
	'226': 'Hazard Warning',
	'228': 'Mosaic',
	'230': 'Jazzy',
	'232': 'Alien Tech',
	'234': 'Damascus & Mahogany',
	'235': 'Skull Study',
	'236': 'Haunted Ghosts',
	'237': 'Spectral Shimmered',
	'238': 'Spirit of Halloween',
	'239': 'Horror Holiday',
	'240': 'Totally Boned',
	'241': 'Electroshocked',
	'242': 'Ghost Town',
	'243': 'Tumor Toasted',
	'244': 'Calavera Canvas',
	'245': 'Snow Covered',
	'246': 'Frost Ornamented',
	'247': 'Smissmas Village',
	'248': 'Igloo',
	'249': 'Seriously Snowed',
	'250': 'Smissmas Camo',
	'251': 'Sleighin\' Style',
	'252': 'Alpine',
	'253': 'Gift Wrapped',
	'254': 'Winterland Wrapped',
	'300': 'Yeti Coated',
	'301': 'Park Pigmented',
	'302': 'Mannana Peeled',
	'303': 'Macaw Masked',
	'304': 'Sax Waxed',
	'305': 'Anodized Aloha',
	'306': 'Bamboo Brushed',
	'307': 'Tiger Buffed',
	'308': 'Croc Dusted',
	'309': 'Piña Polished',
	'310': 'Leopard Printed',
	'390': 'Dragon Slayer',
	'391': 'Smissmas Sweater'
};

exports.wears = [
	'(Factory New)',
	'(Minimal Wear)',
	'(Field-Tested)',
	'(Well-Worn)',
	'(Battle Scarred)'
];

exports.wear = {
	'(Factory New)': 1,
	'(Minimal Wear)': 2,
	'(Field-Tested)': 3,
	'(Well-Worn)': 4,
	'(Battle Scarred)': 5,
	'1': '(Factory New)',
	'2': '(Minimal Wear)',
	'3': '(Field-Tested)',
	'4': '(Well-Worn)',
	'5': '(Battle Scarred)'
};

exports.ETradeOfferState = {
	Invalid: 1,
	Active: 2, // This trade offer has been sent, neither party has acted on it yet.
	Accepted: 3, // The trade offer was accepted by the recipient and items were exchanged.
	Countered: 4, // The recipient made a counter offer
	Expired: 5, // The trade offer was not accepted before the expiration date
	Canceled: 6, // The sender cancelled the offer
	Declined: 7, // The recipient declined the offer
	InvalidItems: 8, // Some of the items in the offer are no longer available (indicated by the missing flag in the output)
	CreatedNeedsConfirmation: 9, // The offer hasn't been sent yet and is awaiting further confirmation
	CanceledBySecondFactor: 10, // Either party canceled the offer via email/mobile confirmation
	InEscrow: 11, // The trade has been placed on hold

	1: 'Invalid',
	2: 'Active',
	3: 'Accepted',
	4: 'Countered',
	5: 'Expired',
	6: 'Canceled',
	7: 'Declined',
	8: 'InvalidItems',
	9: 'CreatedNeedsConfirmation',
	10: 'CanceledBySecondFactor',
	11: 'InEscrow'
};

exports.qualityColors = {
	0: '#B2B2B2',
	1: '#4D7455',
	2: '#8D834B',
	3: '#476291',
	4: '#70550F',
	5: '#8650AC',
	6: '#FFD700',
	7: '#70B04A',
	8: '#A50F79',
	9: '#70B04A',
	11: '#CF6A32',
	12: '#8650AC',
	13: '#38F3AB',
	14: '#AA0000',
	15: '#FAFAFA'
};

exports.paintCanColors = {
	// A Color Similar to Slate
	'5052;6':
		'TbL_ROFcpnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvOvr1MdQ/',
	// A Deep Commitment to Purple
	'5031;6':
		'TeLfQYFp1nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvVs13Vys/',
	// A Distinctive Lack of Hue
	'5040;6':
		'TYffEcEJhnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvXrHVMg0/',
	// A Mann's Mint
	'5076;6':
		'SLKqRMQ59nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvU8z3W20/',
	// After Eight
	'5077;6':
		'TbLfJME5hnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvWdo-dtk/',
	// Aged Moustache Grey
	'5038;6':
		'TeLPdNFslnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvFkHADQU/',
	// An Air of Debonair
	'5063;6':
		'TffPQfFZxnqWSMU5OD2NsHx3oIzChGKyv2yXdsa7g9fsrW0Az__LbZTDL-ZTCZJiLWEk0nCeYPaCiIp23hirHFAG-cX714QglReKMAoGJKO5qBPxRogIVe_DO5xxB4TBB6dJNEKVrtnidHNeVr2C8V0p8gFQg/',
	// An Extraordinary Abundance of Tinge
	'5039;6':
		'SMf6UeRJpnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgv64ewDK8/',
	// Australium Gold
	'5037;6':
		'SMfqIdEs5nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvsjysS5w/',
	// Balaclavas Are Forever
	'5062;6':
		'TaK_FOE59nqWSMU5OD2NgHxnAPzChGKyv2yXdsa7g9fsrW0Az__LbZTDL-ZTCZJiLWEk0nCeYPaCiIp23hirHFAG-cX714QglReKMAoGJKO5qBPxRogIVe_DO5xxB4TBB6dJNEKVrtnidHNeVr2C8V3lcfHzA/',
	// Color No. 216-190-216
	'5030;6':
		'SNcaJNRZRnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvFOcRWGY/',
	// Cream Spirit
	'5065;6':
		'SKevZLE8hnqWSMU5OD2IsHzHMPnShGKyv2yXdsa7g9fsrW0Az__LbZTDL-ZTCZJiLWEk0nCeYPaCiIp23hirHFAG-cX714QglReKMAoGJKO5qBPxRogIVe_DO5xxB4TBB6dJNEKVrtnidHNeVr2C8VQmu5hdU/',
	// Dark Salmon Injustice
	'5056;6':
		'SMcPkeFs1nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvy3dkty0/',
	// Drably Olive
	'5053;6':
		'TRefgYEZxnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvMuQVCSQ/',
	// Indubitably Green
	'5027;6':
		'Tee_lNFZ5nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvm153-6I/',
	// Mann Co. Orange
	'5032;6':
		'SKL_cbEppnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvTFGBHn4/',
	// Muskelmannbraun
	'5033;6':
		'SIfPcdFZlnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvcmoesjg/',
	// Noble Hatter's Violet
	'5029;6':
		'TcePMQFc1nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvgXmHfsU/',
	// Operator's Overalls
	'5060;6':
		'TdcfMQEpRnqWSMU5OD2NoHwHEIkChGKyv2yXdsa7g9fsrW0Az__LbZTDL-ZTCZJiLWEk0nCeYPaCiIp23hirHFAG-cX714QglReKMAoGJKO5qBPxRogIVe_DO5xxB4TBB6dJNEKVrtnidHNeVr2C8V-hQN5Nc/',
	// Peculiarly Drab Tincture
	'5034;6':
		'SKfKFOGJ1nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvG7gZwMo/',
	// Pink as Hell
	'5051;6':
		'SPL_YRQ5hnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgv9O7ytVg/',
	// Radigan Conagher Brown
	'5035;6':
		'TfcPRMEs1nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgv4OlkQfA/',
	// Team Spirit
	'5046;6':
		'SLcfMQEs5nqWSMU5OD2NwHzHZdmihGKyv2yXdsa7g9fsrW0Az__LbZTDL-ZTCZJiLWEk0nCeYPaCiIp23hirHFAG-cX714QglReKMAoGJKO5qBPxRogIVe_DO5xxB4TBB6dJNEKVrtnidHNeVr2C8VWwsKTpY/',
	// The Bitter Taste of Defeat and Lime
	'5054;6':
		'Tae6NMEp5nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvvmRKa6k/',
	// The Color of a Gentlemann's Business Pants
	'5055;6':
		'SPeaUeGc9nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvoDEBbxU/',
	// The Value of Teamwork
	'5064;6':
		'TRefMYE5xnqWSMU5OD2NsKwicEzChGKyv2yXdsa7g9fsrW0Az__LbZTDL-ZTCZJiLWEk0nCeYPaCiIp23hirHFAG-cX714QglReKMAoGJKO5qBPxRogIVe_DO5xxB4TBB6dJNEKVrtnidHNeVr2C8Vs4Ux0YY/',
	// Waterlogged Lab Coat
	'5061;6':
		'SIcflJGc9nqWSMU5OD2NEMzSVdmyhGKyv2yXdsa7g9fsrW0Az__LbZTDL-ZTCZJiLWEk0nCeYPaCiIp23hirHFAG-cX714QglReKMAoGJKO5qBPxRogIVe_DO5xxB4TBB6dJNEKVrtnidHNeVr2C8VT2CQ46M/',
	// Ye Olde Rustic Colour
	'5036;6':
		'TeKvZLFJtnqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvmeRW1Z8/',
	// Zepheniah's Greed
	'5028;6':
		'Tde_ROEs5nqWSMU5PShIcCxWVd2H5fLn-siSQrbOhrZcLFzwvo7vKMFXrjazbKEC3YDlltU7ILYTmKrTT3t-mdE2nBQewrRwpRKfEHoGxPOM3aPhM8045d-zTgwxczDhgvPiWjbeE/'
};

exports.defindexes = {
	'Mann Co. Supply Crate Key': 5021,
	'Lugermorph': 160
};
